version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: political_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=8000
    volumes:
      - ./backend:/app
    depends_on: []

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: political_frontend
    ports:
      - "19006:19006"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - ./frontend:/app
    command: ["yarn", "start", "--web"]
